language: java

sudo: required

jdk:
  - oraclejdk8

install: true

before_script: cd projet-middle/

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
script: mvn package
